This has some code snippets used in the post:
[Getting Data](https://aconai.dev/p/getting-data)

In [2]:
import yfinance as yf

yf.download("AAPL", start="2020-01-01", end="2025-01-01")

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

1 Failed download:
['AAPL']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

Empty DataFrame
Columns: [(Adj Close, AAPL), (Close, AAPL), (High, AAPL), (Low, AAPL), (Open, AAPL), (Volume, AAPL)]
Index: []

In [6]:
from curl_cffi import requests
session = requests.Session(impersonate="chrome")
yf.download("AAPL", start="2020-01-01", end="2025-01-01", session=session)

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2020-01-02   72.716064   72.776591   71.466805   71.721011  135480400
2020-01-03   72.009125   72.771752   71.783969   71.941336  146322800
2020-01-06   72.582901   72.621639   70.876068   71.127858  118387200
2020-01-07   72.241562   72.849239   72.021246   72.592609  108872000
2020-01-08   73.403641   73.706271   71.943751   71.943751  132079200
...                ...         ...         ...         ...        ...
2024-12-24  257.916443  257.926411  255.009620  255.209412   23234700
2024-12-26  258.735504  259.814335  257.347047  257.906429   27237100
2024-12-27  255.309296  258.415896  252.782075  257.546826   42355300
2024-12-30  251.923019  253.221595  250.474615  251.952985   35557500
2024-12-31  250.144974  253.001833  249.156056  252.162760   39480700

[1258 rows x 5 columns]

In [4]:
import yfinance as yf
from curl_cffi import requests

session = requests.Session(impersonate="chrome")
df = yf.download(
    "AAPL",
    start="2020-01-01",
    end="2025-01-01",
    session=session,
    auto_adjust=False,
    actions=True
)
ratio = (df["Adj Close"] / df["Close"]).to_numpy()
df["Adj Open"] = df["Open"] * ratio
df["Adj High"] = df["High"] * ratio
df["Adj Low"] = df["Low"] * ratio

[*********************100%***********************]  1 of 1 completed